apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpaca-prod
  namespace: kuard
  labels:
    app: alpaca
    env: prod
    ver: "1"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alpaca
      env: prod
      ver: "1"
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alpaca
        env: prod
        ver: "1"
    spec:
      containers:
      - image: gcr.io/kuar-demo/kuard-amd64:blue
        name: kuard
