apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: host-ingress
spec:
  rules:
  - host: alpaca.fluster.dcache.dev        
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: alpaca-prod
            port:
              number: 8080
